### ISSUE TITLE
Upgrade to Magento 2.2.4 -  MySQL server has gone away

### ISSUE THREAD

**Issue by zennco** [magefan/module-blog#156]
Your module was installed on Magento 2.2.3

Started an upgrade to 2.2.4 using composer
Then run bin/magento setup:upgrade
As soon as the upgrade reaches Magefan_Blog it fails with a "MYSQL server gone away" error.

`Module 'Magento_Catalog':
Upgrading schema..
Module 'Magefan_Community':
Module 'Magefan_Blog':
Upgrading schema.. Warning: PDOStatement::execute(): MySQL server has gone away in /var/www/ourshop/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228`

We have a dedicated database server
Percona 5.7.21 (MySQL 5.7)
Ubuntu 16.04
Plenty of memory

Probably related to https://github.com/magefan/module-blog/issues/142.

Upgrade works fine if the module is removed.

**Comment by nopenopenope** [comment]
I've had the same issue with another module, just make sure to pass `-dmemory_limit=6GB` to the command: 
https://magento.stackexchange.com/questions/226362/upgrading-from-2-0-6-to-2-2-4/226367#226367

**Comment by nopenopenope** [comment]
Additonally you might wanna change mysqld-configs in my.cnf: 
```

[mysqld]
port            = 3306
table_open_cache               = 1048576
table_definition_cache         = 4096
max_heap_table_size            = 64M
tmp_table_size                 = 64M
max_connections                = 505
max_user_connections           = 500
max_allowed_packet             = 160M

thread_cache_size              = 32
query_cache_size               = 64M

```

**Comment by zennco** [comment]
@nopenopenope suggested solution is just temporary to overcome the Blog module install/upgrade problem. Please take a look at http://php.net/manual/en/ini.core.php#ini.memory-limit. 
Complex scripts can run even with less than 1GB. Though, some loops or dumping of big objects might use all the available memory limit no matter how big. Unless is 6GB maybe :), which is very unusual, even for Magento 2 (it uses only 768MB in standard install, sometimes 1-2GB when it needs some core changes).

@magefan please re-open the issue. The solution is just temporary. Please provide a permanent one.

**Comment by nopenopenope** [comment]
I can verify that the bug exists again on a production server. 

Even with another tone of the demanding request to provide a solution for that bug, I'd love to see some ideas from @magefan on how to solve this problem. 

Additionally, with the latest update I'm not even able to proceed `setup:upgrade` when adding the memory_limit, so now we somewhere have a bug I guess. Looking at the InstallSchema doesn't really tell me a thing, as it all seems okay.

**Comment by nopenopenope** [comment]
@magefan Sadly I don't have a propper env anymore as I were able to fix it.

I solved my problem while having this setup:
* local env for development
* testing env on production server
* production env on production server

I start at my local env (Production Backup installed with Magefan Blog from 2.0.6). We have a fair amount of entries here, around 200. 
I try to upgrade with `php bin/magento setup:upgrade`. THIS FAILS.

If I add `-d memory_limit=6G` to the command, it works. 

I cannot do it without this. On `stage` and `production`, I cannot upgrade as well, as the server runs out of memory and fails due to failed allocation of RAM. 

My final workaround was to import a dump of the Production server, upgraded it locally, dumped the DB from local and imported it into Stage and Production. Now everything works, also minor upgrades of Magefan Blog.

So my assumption is, that Magefan uses the `Upgrade`-functionality of M2 in such a way were a tmp table gets created on the RDBMS instance which has a overflow somewhere which finally leads to RAM leaks. The problem does appear if you try to upgrade directly from a very old version to the latest version. 

Hopefully this helps anyone with similar problems and gives anyone a good startingpoint in debugging this.

**Comment by laciborzos** [comment]
@zennco 

i had the same problem with the 2.8.0 version. There's a line of code in [UpgradeSchema.php](https://github.com/magefan/module-blog/blob/b20c51c8b06930e7ebc141b45935f9a93309f851/Setup/UpgradeSchema.php#L555)
`$connection->addColumn(
                $setup->getTable($table),
                'is_active',
                [
                    'type' =>\Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
                    'length' => null,
                    'nullable' => false,
                    'default' => 1,
                    'comment' => 'Is Tag Active'
                ]
            );`
this code,and the `length` is `null`, if i set it to a number,it the `setup:upgrade` command works. otherwise it says that the `mysql has gone away`. Maybe it helps.

**Comment by magefan** [comment]
@laciborzos , thank you, for your suggestion, we will check

**Comment by magefan** [comment]
@laciborzos , we have added code changes
https://github.com/magefan/module-blog/commit/dc6f8fa7dbd6579a06cfdd3f062084e737641bda

The problem is that we cannot reproduce this mysql server issue on our test environment.  
So if anyone will have the same issue and use the fix we have done today, let us know.

**Comment by magefan** [comment]
In case anyone still have this issue, you can try to remove some deprecated blog post FULLTEXT indexes before update the extension. For this run SQL query:

> ALTER TABLE magefan_blog_post DROP INDEX MAGEFAN_BLOG_POST_TITLE;
> ALTER TABLE magefan_blog_post DROP INDEX MAGEFAN_BLOG_POST_CONTENT;
> ALTER TABLE magefan_blog_post DROP INDEX MAGEFAN_BLOG_POST_SHORT_CONTENT;
