### ISSUE TITLE
Cannot remove addthis

### ISSUE THREAD

**Issue by djinnsour** [magefan/module-blog#267]
In the [Magento 2 Blog](https://magefan.com/magento2-blog-extension) settings if you set AddThis Enabled to No it still shows up on the blog pages. Newest version from magefan-blog-2.9.0.1.zip downloaded from Magefan site.

**Comment by magefan** [comment]
Hello @djinnsour , thank you for your report. Unfortunately, we were not able to reproduce this issue on vanilla Magento installation. Also, we cannot reproduce the issue on our [Magento 2 Blog Demo](https://blog.demo.magefan.top/admin/).

We think that most likely the issue is related to customizations you have, especially overridden blog templates and layouts in your theme.
Please check folder
app/design/frontend/ThemeVendor/themename/Magefan_Blog

If doe's not helped let us know.

**Comment by magefan** [comment]
Closed ticket due to inactivity.
