### ISSUE TITLE
No PHP 7.4 support

### ISSUE THREAD

**Issue by dawid-fwc** [magefan/module-blog#336]
Blog is ready for Magento 2.4 but Magento support PHP 7.4 and blog not.
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in /var/www/vendor/magefan/module-blog-author/Model/Author.php on line 166

**Comment by ihorvansach** [comment]
@dawid-fwc , this issue was fixed in the magefan/module-blog-author v2.9.6.1 you can get it via the composer or as archive from your Magefan account 
https://magefan.com/downloadable/customer/products/
If you will go with the archive, please note that blog-author is included into blog extra archive.

Please contact magefan via support@magefan.com in case you need further assistance with this issue.
