### ISSUE TITLE
Approving comments sets an incorrect time

### ISSUE THREAD

**Issue by parvesh-r** [magefan/module-blog#366]
Approving comments causes the time to be all messed up.
I am on the dk locale.

**Comment by magefan** [comment]
Thank you for your report @parvesh-r.

Could you please Preconditions, Steps to reproduce , Expected result  and  Actual result 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---

**Comment by magefan** [comment]
We're closing this ticket due to inactivity.
Just as the suggestion. Please check the database table magefan_blog_comment and make sure that it's structure is

CREATE TABLE `magefan_blog_comment` (
  `comment_id` int NOT NULL COMMENT 'Comment ID',
  `parent_id` int NOT NULL COMMENT 'Parent Comment ID',
  `post_id` int NOT NULL COMMENT 'Post ID',
  `customer_id` int DEFAULT NULL COMMENT 'Customer ID',
  `admin_id` int DEFAULT NULL COMMENT 'Admin User ID',
  `status` smallint NOT NULL COMMENT 'Comment status',
  `author_type` smallint NOT NULL COMMENT 'Author Type',
  `author_nickname` varchar(255) NOT NULL COMMENT 'Comment Author Nickname',
  `author_email` varchar(255) DEFAULT NULL COMMENT 'Comment Author Email',
  `text` mediumtext COMMENT 'Text',
  `creation_time` timestamp NULL DEFAULT NULL COMMENT 'Comment Creation Time',
  `update_time` timestamp NULL DEFAULT NULL COMMENT 'Comment Update Time'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='magefan_blog_comment';

Pay attention to columns creation_time and update_time make sure that it does not have any auto update on save values like current timestamp.
