### ISSUE TITLE
Reversed exception being thrown preventing developers from searching

### ISSUE THREAD

**Issue by mshererSO** [magefan/module-blog#451]
You are throwing an exception in your blog module with the seeming intent of preventing developers from finding the message. It would be nice to get some context as to why you chose to do this and what it is meant to accomplish.

File: vendor/magefan/module-blog/Controller/Adminhtml/Import/Form.php

`
if (!$this->getConfig()->isEnabled()) {
    throw new LocalizedException(__(strrev('golB > snoisnetxE nafegaM > noitarugifnoC > serotS ni noisnetxe golb elbane esaelP')));
}
`

**Comment by magefan** [comment]
@mshererSO , Since PHP is open source anyone can edit the code. This part is intended to cause at least some pain to those who try to disable our licensing system and use the module in violation of our license agreement. That is why we use strrev to make the text hard to find just using regular "search in files". You have no idea how widespread piracy is, even in the world of e-commerce :-(
