### ISSUE TITLE
/blog index page keeps working after changing blog route in settings

### ISSUE THREAD

**Issue by jornwildenbeest** [magefan/module-blog#499]
**Describe the bug**
Goal: I want to change the slug of the blog index page.

Not sure if this is default behaviour or a bug. But it is not behaviour that I expected.
When changing the blog route in settings to /blogindex for example, /blog keeps working.

/blog is still working, you would expect that only /blogindex works.

**Preconditions:**
 - Magento Version: 2.4.5-p1
 - Module Version: 2.10.13
 - PHP Version 8.1

**To Reproduce**
1. Go to settings
2. Change blog index route to something else.
3. Visit /blog
4. This is still working while we changed the blog index route

**Comment by magefan** [comment]
@jornwildenbeest , that is expected behavior as the "blog" is also the module route frontend name https://github.com/magefan/module-blog/blob/master/etc/frontend/routes.xml (a technical path).

When you change the blog route to the blogindex all blog URLs are now working with this new route, but /blog is still available.
On /blog page you can see the canonical URL that leads to blogindex, this helps with fixing page duplication.
If you want you can make 301 redirects on the webserver level to 301 redirects from /blog to /blogindex

Similar behavior you can see in the catalog. For example, each product  has a technical URL /catalog/product/view/id/PRODUCT ID, e.g. https://blog.demo.magefan.top/joust-duffle-bag.html has technical URL https://blog.demo.magefan.top/catalog/product/view/id/1

Let us know if it makes sense for you.
