### ISSUE TITLE
EM Themes Blog for Magento 2 / EM Blog

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/module-blog#615]

**Comment by magefan** [comment]
<p>If you use (or have used)&nbsp;<strong>EM Blog &amp; News</strong>&nbsp;extension on your Magento 1 store, and now you're migrating to Magento 2, you can have a problem because EM Theme does not provide&nbsp;Blog extension for M2.</p>
<p>Fortunately, you can use <a title="Free Magento 2 Blog Module" href="{{store url=magento2-blog-extension}}" target="_blank" rel="noopener">Magento 2 Blog extension</a>&nbsp;by Magefan, what has a lot of features and it's free. Our team can help&nbsp;you to migrate all blog data such as posts, categories, tags, comments, images to your new store on Magento 2.</p>
<p style="text-align: center;"><a class="btn-col-green" style="color: white;" title="Get a quote" href="https://magefan.com/contact/" target="_blank" rel="noopener">Request a Quote Today</a></p>
